// Listen to item tag event
ServerEvents.tags('item', event => {


  // Disabled Items
  const removeTags = [

    //Tools
    'minecraft:wooden_shovel',
    'minecraft:wooden_pickaxe', 
    'minecraft:wooden_hoe', 
    'minecraft:wooden_sword', 
    'minecraft:wooden_axe',
    'minecraft:stone_shovel', 
    'minecraft:stone_pickaxe', 
    'minecraft:stone_axe',
    'minecraft:stone_hoe',

    // Flint Armor
    'pickletweaks:flint_helmet', 
  'pickletweaks:flint_chestplate', 
  'pickletweaks:flint_leggings', 
  'pickletweaks:flint_boots', 

    // Zinc
      'create:zinc_ingot', 
      'create:zinc_nugget', 
      'create:zinc_block', 
      'createaddition:zinc_sheet', 
      'spelunkery:raw_zinc_nugget', 
      'create:crushed_raw_zinc', 
      'create:raw_zinc',
      'create:raw_zinc_block', 
      'create:zinc_ore', 
      'create:deepslate_zinc_ore', 
      'spelunkery:andesite_zinc_ore', 
      'spelunkery:diorite_zinc_ore', 
      'spelunkery:granite_zinc_ore',

    //Brass
    'create:brass_ingot',
    'create:brass_nugget',
    'create:brass_sheet',
    'create:brass_block',
    'createaddition:brass_rod',
    
    //RandomStuff
    'meadow:woodcutter',
    'meadow:cooking_cauldron',
    'meadow:frame',

    //Wood
    'biomesoplenty:palm_sapling', 
    'biomesoplenty:palm_leaves', 
    'biomesoplenty:palm_log', 
    'biomesoplenty:stripped_palm_log', 
    'biomesoplenty:palm_wood', 
    'biomesoplenty:stripped_palm_wood', 
    'biomesoplenty:palm_planks', 
    'biomesoplenty:palm_slab', 
    'biomesoplenty:palm_stairs', 
    'biomesoplenty:palm_fence', 
    'biomesoplenty:palm_fence_gate', 
    'biomesoplenty:palm_door', 
    'biomesoplenty:palm_trapdoor', 
    'biomesoplenty:palm_pressure_plate', 
    'biomesoplenty:palm_button', 
    'biomesoplenty:palm_sign', 
    'biomesoplenty:palm_boat', 
    'biomesoplenty:palm_chest_boat', 

    'regions_unexplored:palm_sapling', 
    'regions_unexplored:palm_leaves', 
    'regions_unexplored:palm_log', 
    'regions_unexplored:stripped_palm_log', 
    'regions_unexplored:palm_wood', 
    'regions_unexplored:stripped_palm_wood', 
    'regions_unexplored:palm_planks', 
    'regions_unexplored:palm_stairs', 
    'regions_unexplored:palm_slab', 
    'regions_unexplored:palm_fence', 
    'regions_unexplored:palm_door', 
    'regions_unexplored:palm_fence_gate', 
    'regions_unexplored:palm_trapdoor', 
    'regions_unexplored:palm_pressure_plate', 
    'regions_unexplored:palm_button', 
    'regions_unexplored:palm_sign', 
    'regions_unexplored:palm_hanging_sign', 
    'regions_unexplored:palm_boat',
    'regions_unexplored:palm_chest_boat',

    'meadow:pine_sign', 
      'meadow:pine_hanging_sign', 
      'meadow:pine_boat', 
      'meadow:pine_chest_boat', 
      'meadow:pine_button', 
      'meadow:pine_log', 
      'meadow:pine_wood', 
      'meadow:stripped_pine_wood', 
      'meadow:stripped_pine_log', 
      'meadow:pine_planks', 
      'meadow:pine_stairs', 
      'meadow:pine_slab', 
      'meadow:pine_pressure_plate', 
      'meadow:pine_trapdoor', 
      'meadow:pine_door', 
      'meadow:pine_fence', 
      'meadow:pine_fence_gate',
      'meadow:pine_sapling', 
      'meadow:pine_leaves', 
      'meadow:alpine_birch_leaves_hanging',

    // Stones
    'meadow:alpine_salt_ore', 
    'meadow:alpine_coal_ore', 
    'meadow:alpine_lapis_ore', 
    'meadow:alpine_gold_ore', 
    'meadow:alpine_emerald_ore', 
    'meadow:alpine_iron_ore', 
    'meadow:alpine_copper_ore', 
    'meadow:alpine_diamond_ore', 
    'meadow:alpine_redstone_ore', 
    'meadow:limestone', 
    'meadow:limestone_stairs', 
    'meadow:limestone_slab', 
    'meadow:cobbled_limestone', 
    'meadow:cobbled_limestone_stairs',
    'meadow:cobbled_limestone_slab', 
    'meadow:limestone_bricks', 
    'meadow:limestone_brick_stairs', 
    'meadow:limestone_brick_slab', 
    'meadow:mossy_cobbled_limestone', 
    'meadow:mossy_cobbled_limestone_stairs', 
    'meadow:mossy_cobbled_limestone_slab', 
    'meadow:mossy_limestone_bricks', 
    'meadow:mossy_limestone_brick_stairs', 
    'meadow:mossy_limestone_brick_slab', 
    'meadow:cracked_limestone_bricks', 
    'meadow:chiseled_limestone_bricks', 
    'meadow:polished_limestone_bricks', 
    'meadow:limestone_wall', 
    'meadow:cobbled_limestone_wall', 
    'meadow:limestone_brick_wall', 
    'meadow:mossy_cobbled_limestone_wall', 
    'meadow:mossy_limestone_brick_wall',

    //Botania
    'botania:apothecary_default', 
        'botania:apothecary_mossy', 
        'botania:apothecary_livingrock', 
        'botania:apothecary_deepslate',
    'botania:apothecary_forest', 
      'botania:apothecary_plains', 
      'botania:apothecary_mountain', 
      'botania:apothecary_fungal', 
      'botania:apothecary_swamp', 
      'botania:apothecary_desert', 
      'botania:apothecary_taiga', 
      'botania:apothecary_mesa'

    /*
    // Stone Tools
    'minecraft:enchanting_table',
    'minecraft:shulker_shell',
    'tconstruct:enderman_head',
    'quark:granite_pillar', 
    'quark:diorite_pillar', 
    'quark:andesite_pillar', 
    'create:tuff_pillar', 
    'quark:calcite_pillar', 
    'quark:dripstone_pillar',
    'minecraft:gold_ore',
    'minecraft:deepslate_gold_ore',
    'spelunkery:andesite_gold_ore',
    'spelunkery:diorite_gold_ore',
    'spelunkery:granite_gold_ore',
    'spelunkery:tuff_gold_ore',
    'caverns_and_chasms:silver_ingot',
    'caverns_and_chasms:silver_nugget',
    'caverns_and_chasms:silver_block',
    'caverns_and_chasms:raw_silver',
    'caverns_and_chasms:raw_silver_block',
    'caverns_and_chasms:silver_ore',
    'galosphere:silver_ingot',
    'galosphere:silver_nugget',
    'galosphere:silver_block',
    'galosphere:raw_silver',
    'galosphere:raw_silver_block',
    'galosphere:silver_ore',
    'galosphere:deepslate_silver_ore',
    'oreganized:silver_ore',
    'oreganized:deepslate_silver_ore',
    'spelunkery:andesite_silver_ore',
    'spelunkery:diorite_silver_ore',
    'spelunkery:granite_silver_ore',
    'spelunkery:tuff_silver_ore',
    'create:zinc_ingot',
    'create:zinc_nugget',
    'create:zinc_block',
    'create:raw_zinc',
    'create:raw_zinc_block',
    'spelunkery:raw_zinc_nugget',
    'create:crushed_raw_zinc',
    'create:raw_zinc_block',
    'create:zinc_ore',
    'create:deepslate_zinc_ore',
    'spelunkery:andesite_zinc_ore',
    'spelunkery:diorite_zinc_ore',
    'spelunkery:granite_zinc_ore',
    'create:brass_ingot',
    'create:brass_nugget',
    'create:brass_sheet',
    'create:brass_block',
    'createaddition:electrum_ingot',
    'createaddition:electrum_nugget',
    'createaddition:electrum_block',
    'createaddition:brass_rod',
    'tconstruct:cobalt_ingot',
    'tconstruct:cobalt_nugget',
    'tconstruct:cobalt_block',
    'tconstruct:raw_cobalt',
    'tconstruct:raw_cobalt_block',
    'tconstruct:cobalt_ore',
    'tconstruct:gold_bars',
    //'tconstruct:rose_gold_block',
    'spelunkery:wooden_channel',
    'spelunkery:wooden_sluice',
    'spelunkery:stone_channel',
    'spelunkery:stone_sluice',
    'caverns_and_chasms:calcite_stairs',
    'caverns_and_chasms:calcite_wall',
    'caverns_and_chasms:calcite_slab',
    'caverns_and_chasms:tuff_stairs', 
    'caverns_and_chasms:tuff_slab', 
    'caverns_and_chasms:tuff_wall', 
    'caverns_and_chasms:polished_tuff', 
    'caverns_and_chasms:polished_tuff_stairs', 
    'caverns_and_chasms:polished_tuff_slab',
    'create:crushed_raw_osmium',
    'create:crushed_raw_platinum',
    'create:crushed_raw_tin',
    'create:crushed_raw_quicksilver',
    'create:crushed_raw_nickel',
    'create:crushed_raw_uranium',
    'create:crushed_raw_aluminum',
    'create:experience_nugget',
    'create:experience_block',
    'create:sand_paper',
    'create:red_sand_paper',
    'create:handheld_worldshaper',
    'create:creative_motor',
    'create:creative_fluid_tank',
    'create:creative_crate',
    'create:creative_blaze_cake',
    'oreganized:bush_hammer',

    // Farmers Delight
    'farmersdelight:flint_knife',

    // Quark Tuff Blocks
    'quark:polished_tuff', 
    'quark:tuff_bricks', 
    'quark:chiseled_tuff_bricks', 
    'quark:tuff_bricks_wall', 
    'quark:tuff_bricks_slab', 
    'quark:tuff_bricks_stairs', 
    'quark:tuff_slab', 
    'quark:tuff_stairs', 
    'quark:polished_tuff_slab', 
    'quark:polished_tuff_stairs',
    'quark:tuff_wall'

*/
    
  ];

  removeTags.forEach((item) => {
    event.removeAllTagsFrom(item)
    event.add('girlfriendcraft:disabled', item)
  });

})